if: tag IS blank
language: node_js
node_js:
- node
matrix:
  include:
  - sudo: required
    dist: trusty
    addons:
      chrome: stable
    licenses:
    - android-sdk-preview-license-.+
    - android-sdk-license-.+
    - google-gdk-license-.+
    before_script:
    - echo hi
    script:
    - cd AttendanceService
    - mvn install
    - cd target
    - rm -fr AttendanceService-0.0.1-SNAPSHOT
    - unzip AttendanceService-0.0.1-SNAPSHOT.war
    - cp ../src/config.yaml WEB-INF/classes/
    - zip -r AttendanceService.war WEB-INF META-INF
    - pwd
    - sudo apt-get install tomcat8 --yes
    - sudo rm -fr /var/lib/tomcat8/webapps/ROOT
    - sudo cp AttendanceService.war /var/lib/tomcat8/webapps/ROOT.war
    - sudo apt-get install mysql-server --yes
    - echo "GRANT ALL PRIVILEGES ON *.* TO 'picrin'@'localhost' IDENTIFIED BY 'password';" | sudo mysql -u root
    - cd ../..
    - mysql -u picrin --password=password < database.dump
    - sleep 10
    - curl -H "Content-type:application/json" -X POST 127.0.01:8080/rest/login --data '{"guid": "admin", "password": "alwyn96327011"}' -c - | awk '{print $7}' | tail -n 1 > token
    - token=$(cat token)
    - curl -H "Content-type:application/json" -X POST 127.0.01:8080/rest/getGroups --data '{"guid": "admin"}' --cookie "token=$token" > answer
    - if grep -q CS1P answer; then echo "0"; else exit 1; fi
deploy:
  provider: releases
  api_key:
    secure: BbgwNcQlQ5WRrkf6f53uzBaYEnpw7pKFelJ1Wxkok4QBmnLSNVu/3fiE2AXltsohwfW+yRKcTwjj24kzZICqxF7aDRb3QtQWgWhd4su6Xqe0Y+iL4E5Q8o/Ax2+DuuJxB4vERUfwFC79RaydybzsRngVtd4zsKNwX+cIY9FFaUbxC/log0dhjx9dsWRfeX/5mDgbocviN3fj4fDXI7u5uXoNgt5DN7VkOS32oHNOi9TYrRmWgD4GVhnmWNdn35PfleXibcTosatGETxlaiPXBcBne56xHoGJwKmLgwT/khbcawhZNSJYUAKAQypKhhD2HZq+WhFr4d03zQalA8IytjPJFFmT8Be0+htAtNnsa+mBHDOVLYiXP1Jn49LM6Z4Mup3BwHfQOqeFa7/117bxs23/rQty9owjlcOGi7Zvef5EhpvIJRBkpABtlVGA0RHl2wWNX7ph5D1JvItzW08C6eNm2u8DaKGAkRMEff7MCdD77t2Vv4/FtgW1CnuLzd4QHC3MESSM4sT8nn2W3FluRUxjr/dG7PoqARequDylPzUwwkFHKqQT+djPmrsFQ62SIGl3PIqjISdhPpgodf8lt6dyzDFBguS747M0hzJSnUKLCAzxADKQFCJKCWRilAt0pfuodI2tpPU5vT4CNFCSS9f2g7a3ujzitrinyJ1ASgc=
  skip_cleanup: true
  file: /home/travis/build/picrin/attendanceTrack/AttendanceService/target/AttendanceService.war
  on:
    repo: picrin/attendanceTrack
