if: tag IS blank
language: node_js
node_js:
- node
matrix:
  include:
  - sudo: required
    dist: trusty
    addons:
      chrome: stable
    licenses:
    - android-sdk-preview-license-.+
    - android-sdk-license-.+
    - google-gdk-license-.+
    before_script:
    - echo hi
    script:
    - cd AttendanceService
    - mvn install
    - cp src/config.yaml target/AttendanceService-0.0.1-SNAPSHOT/WEB-INF/classes/
    - zip -r AttendanceService.war target/AttendanceService-0.0.1-SNAPSHOT
    deploy:
      provider: releases
      api_key: GITHUB OAUTH TOKEN
      file: FILE TO UPLOAD
      skip_cleanup: true
deploy:
  provider: releases
  api_key:
    secure: UkQqYGeVJzcxXGMgOLsKeuUKjPQ4Ix+rfR59AeENe9Y0+WtM0zyGCYvsU/yhZBNyfuIRlAzCLRPk0428jas4YCgs4Z53FTF3xLqsEscCosxanF9p1yqdTkLtWhizmnuxAhaHbIiOYaELu3gs22k3x+x4BT0gJqdP9L7tBHV8auTGHlSEUXc/Gpngwh87NfxvucaaLsGU1mhemh05kXBHJoeXcMru8cpCyPLumYaLn50bvMoBIMpNnGgD1G6RuHGtJB9FwpJXBJnBTWcNI8rFMLmS5PoRPm61cjDGS2mDKdmz+2GryUfUlynWpbenftPowtqA7GFNipZhgv87QL7LiNmxI14VeuxqTkS96rHWxpC/tCFG3MF+koNppTshWCWvhkDob7s0nW69WzxXoAN/nmuUdfo0A1RRiiDltW1Sg83cFWm4Je/bc1uIoLL4Arbwp6QpvU7SREu8xMxeRdOVNSHD0WYig0JAsqJDXpFyJiMeMDJbTHq5Z641GDKZu2SWba3e4HcL57PGaM5qy2wtWYlHpiqGQGXeb8VCCkr0Dj6xoKOm0UxbxHGmPbXegd+sLhIGGSr1BJR4e5pdUOWdueLVmphJ7cvWVtvVZzdmEFGMKZ9g3KWGrZnS1fXIZ7HB0J6qQbX2cBfhZ/rwCvCkOulAE9+JA3DKBppzIM5Oyqo=
  file: AttendanceService/AttendanceService.war
