if: tag IS blank
language: node_js
node_js:
  - 'node'
matrix:
  include:
    -
      sudo: required
      dist: trusty
      addons:
        chrome: stable
      licenses:
        - android-sdk-preview-license-.+
        - android-sdk-license-.+
        - google-gdk-license-.+
      before_script:
        - 'echo hi'
      script:
        - 'cd AttendanceService'
        - 'mvn install'
